### ISSUE TITLE
Why is source embedded in .zip files?

### ISSUE THREAD

**Issue by andrew-elder** [OCAAlliance/ocaalliance.github.io#1]
Can't really collaborate / fork / pull request with the source code is packaged in .zip files. Is there a plan to use github as a collaborative platform?

**Comment by arneg** [comment]
We have been talking about that and it would certainly make collaboration easier. The current problem is that the code exists in private repositories and not everyone has decided yet, if they are happy with exporting those to github.

In my opinion it would be ideal to create new repositories for those and simply link to them.

**Comment by andrew-elder** [comment]
Oh, I see the dilemma. I didn't think of that. Yes, new repos without "public" code should work ok if folks can commit to it.

**Comment by tljdebrouwer** [comment]
Code can now be found at https://github.com/OCAAlliance/OCAMicro.
